### ISSUE TITLE
Ability to specify GitHub user repos

### ISSUE THREAD

**Issue by shanecav84** [jonhadfield/soba#56]
I'm a part of a bunch of repos that I don't want to backup. Specifically, I'd like to only backup repos under my username. I guess an envvar for accept/deny lists for usernames would work.

**Comment by jonhadfield** [comment]
Makes sense. What's odd is the query I'm running should only return: "A list of repositories that the user owns". I've tested and it does still return those I collaborate on.  
I don't want to make a breaking change, i.e. limiting to user owned by default, so thinking the simplest implementation would be a boolean: yes/no(default) on new env var: `GITHUB_USER_OWNED` where I run an additional filter to limit to repos where your login/username is the repository owner.  
It doesn't prevent me adding `GITHUB_OWNERS` later on, but that will take a bit more work to get right.

**Comment by shanecav84** [comment]
Thanks for the consideration. And thanks for the project. Im glad for your active maintenance.

I think the repos returned has to do with GitHub's classic access token having too broad permissions. Implementing the new access tokens would probably help but I know those are more complicated. 

Thanks again.

**Comment by jonhadfield** [comment]
Thanks for your feedback. Really appreciate it.  

I directly use the newer GraphQL (rather than REST) API and a limitation was that it only supported classic tokens. It's now caught up and supports the fine grained personal access tokens too. I did have a play with it, with a PAT only allowing access to specific repos, but what happens is it still returns all the non-private repos you're affiliated with, so not quite what you're after.   
I've worked out how to get the user owned only (minor query change) so will use that version of the query if you set `GITHUB_USER_OWNED` to `yes`. Will get a release out asap.

**Comment by shanecav84** [comment]
> with a PAT only allowing access to specific repos, but what happens is it still returns all the non-private repos you're affiliated with

Hoo boy. I see why they're coming up with a new system.

> Will get a release out asap.

Thanks!

**Comment by jonhadfield** [comment]
New release pushed: https://github.com/jonhadfield/soba/releases/tag/1.2.12  
I opted for `GITHUB_LIMIT_USER_OWNED` in the end. Set that to true and it should do what you need.

**Comment by shanecav84** [comment]
Already got it in installed and it's working great. Thanks again!
