### ISSUE TITLE
Access to Private Organization Repos?

### ISSUE THREAD

**Issue by jacobgraf** [jonhadfield/soba#7]
This seems to work great, but I don't see any of the repos from the GitHub Organization I'm the admin of. Is there a way to tweak this to get those to pull in as well? Thanks!

**Comment by jonhadfield** [comment]
I think it'll require extra configuration; You can be a member of many organisations, so it could result in a user cloning hundreds or thousands of repositories. I want to keep this as simple as possible, with a few env vars for config, but will take a look to see what's possible.

**Comment by jonhadfield** [comment]
I've released [1.1.1](https://github.com/jonhadfield/soba/releases/tag/1.1.1) that adds the ability to back up organisations.  
Rather than automatically back up the repos in all organisations the user has access to, you need to specify a list of organisations you want to include, e.g.:   
GITHUB_ORGS="ThisOrg,ThatOrg". 
Please re-open if you have any issues with this.

**Comment by jacobgraf** [comment]
You rock! Thanks so much!

**Comment by jacobgraf** [comment]
Works like a champ BTW! 👏🏻

**Comment by jonhadfield** [comment]
Great. Thanks for the feedback.
